# cadastrar usuário;
POST http://localhost:9000/alunos/cadastro
Content-Type: application/json


{
    "nome":"Antonio"
}

###

GET http://localhost:3000/listaTodos
###

GET http://localhost:3000/listarcompartilhar

###
# cadastrar usuário;
POST http://localhost:3000/criarcompartilhar
Content-Type: application/json


{
         "destino_bus":"324234",
       " usuario_id":"432432432",
       "localizacao_atual_bus":[ {"cidade":"maceio", "coord": 378348, "Evdd":}],
        "compartilhando": false
}


# jfhdjhjvfd


###
# pega dados de todos os usuarios;
GET http://localhost:3000/api/usuarios
###
# pega dados de todos os usuarios;
GET http://localhost:3000/listarcompartilhar
###
# pega dados de todos os usuarios;
GET http://localhost:3000/api/recuperarsenha


###
# pega dados de um certo usuario;
GET http://localhost:3000/api/dados/648b7b8898e3852f6eaaae17

###
#apaga usuário através do id
DELETE http://localhost:3000/api/usuarios/648b7b88e3852f6eaaae17
###
#apaga todos os usuários;
DELETE http://localhost:3000/api/usuarios


###
#atualizar dados;
PUT http://localhost:3000/api/usuarios/6488d55c9484e7c6528de56a
Content-Type: application/json

{
    "nome":"Antonio",
    "sobrenome":"Victor",
    "email": "aluno.ifal@irineu",
    "senha":"testeteste"
}


# instalar exterão REST