
GET http://localhost:9000/ecommerce/todosproducts
###

GET http://localhost:9000/ecommerce/todospacks

###
#atualizar dados;
PUT http://localhost:9000/ecommerce/atualizarpreco
Content-Type: application/json

{
    "codigo":18,
    "novoPreco":109
}

